import type { PlayerStats, Session } from "./types";

export const demoSessions: Session[] = [
  {
    id: "session-001",
    title: "Saturday Sunrise Rally",
    sport: "Pickleball",
    venue: "Riverside Courts",
    city: "Metro Area",
    date: "2026-08-30",
    dayLabel: "SUN",
    time: "7:00 AM – 9:00 AM",
    level: "Beginner friendly",
    format: "Open play · Rotating doubles",
    price: 220,
    capacity: 16,
    joined: 13,
    waitlist: 0,
    organizer: "Rally Community",
    accent: "lime",
    players: [
      {
        id: "p1",
        name: "Player 01",
        initials: "P1",
        level: "3.0",
        color: "#f97068",
      },
      {
        id: "p2",
        name: "Player 02",
        initials: "P2",
        level: "2.5",
        color: "#7f56d9",
      },
      {
        id: "p3",
        name: "Player 03",
        initials: "P3",
        level: "3.0",
        color: "#2e90fa",
      },
      {
        id: "p4",
        name: "Player 04",
        initials: "P4",
        level: "2.5",
        color: "#f79009",
      },
    ],
  },
  {
    id: "session-002",
    title: "After Work Smash",
    sport: "Badminton",
    venue: "Central Badminton Hall",
    city: "Metro Area",
    date: "2026-08-31",
    dayLabel: "MON",
    time: "6:30 PM – 9:00 PM",
    level: "Intermediate",
    format: "Queue play · Doubles",
    price: 180,
    capacity: 20,
    joined: 18,
    waitlist: 3,
    organizer: "Shuttle Community",
    accent: "violet",
    players: [
      {
        id: "p5",
        name: "Player 05",
        initials: "P5",
        level: "B",
        color: "#12b76a",
      },
      {
        id: "p6",
        name: "Player 06",
        initials: "P6",
        level: "B+",
        color: "#ee46bc",
      },
      {
        id: "p7",
        name: "Player 07",
        initials: "P7",
        level: "B",
        color: "#6172f3",
      },
    ],
  },
  {
    id: "session-003",
    title: "Midweek Dink & Drink",
    sport: "Pickleball",
    venue: "Northside Sports Hub",
    city: "Metro Area",
    date: "2026-09-02",
    dayLabel: "WED",
    time: "5:30 PM – 7:30 PM",
    level: "All levels",
    format: "Social open play",
    price: 250,
    capacity: 12,
    joined: 7,
    waitlist: 0,
    organizer: "Dink Community",
    accent: "lime",
    players: [
      {
        id: "p8",
        name: "Player 08",
        initials: "P8",
        level: "3.5",
        color: "#f63d68",
      },
      {
        id: "p9",
        name: "Player 09",
        initials: "P9",
        level: "3.0",
        color: "#15b79e",
      },
    ],
  },
];

export const demoStats: PlayerStats = {
  matches: 28,
  wins: 18,
  losses: 10,
  winRate: 64,
  streak: 4,
  rating: 3.12,
  recentForm: ["W", "W", "L", "W", "W"],
};
