"""Initial sport catalog. This module is data.

Rows are inserted once when missing and never overwritten, so edits made by
administrators through the API survive restarts. See docs/ARCHITECTURE.md §1
for what each configuration block means.
"""

CATEGORIES = [
    ("racket_paddle", "Racket and paddle sports"),
    ("team_court", "Team and court sports"),
    ("bat_field", "Bat, ball and field sports"),
    ("indoor_recreational", "Indoor and recreational sports"),
    ("fitness_activity", "Fitness and activity-based sports"),
    ("outdoor_specialty", "Outdoor and specialty sports"),
]

RESOURCE_TYPES = [
    ("court", "Court"),
    ("half_court", "Half court"),
    ("field", "Field"),
    ("half_field", "Half field"),
    ("lane", "Lane"),
    ("table", "Table"),
    ("studio", "Studio"),
    ("pool", "Pool"),
    ("pool_lane", "Pool lane"),
    ("training_area", "Training area"),
    ("ring", "Ring"),
    ("tee", "Tee"),
    ("climbing_wall", "Climbing wall"),
    ("track", "Track"),
    ("skate_park", "Skate park"),
    ("station", "Station"),
    ("other", "Other"),
]

GENERAL_LEVELS = ["All levels", "Beginner", "Intermediate", "Advanced"]


def _formats(*items: tuple[str, str, int]) -> list[dict]:
    return [{"id": key, "label": label, "playersPerSide": size} for key, label, size in items]


SINGLES_DOUBLES = _formats(("singles", "Singles", 1), ("doubles", "Doubles", 2), ("mixed_doubles", "Mixed doubles", 2))


def _two_sided(kind: str, unit: str, *, best_of: int | None = None, game_label: str = "", allow_draw: bool = False, player_fields=()):
    return {
        "kind": kind,
        "unit": unit,
        "bestOf": best_of,
        "gameLabel": game_label,
        "allowDraw": allow_draw,
        "playerFields": [{"key": key, "label": label} for key, label in player_fields],
        "activityFields": [],
        "aggregations": [],
    }


def _individual(fields: list[dict], aggregations: list[dict]) -> dict:
    return {
        "kind": "individual",
        "unit": "",
        "bestOf": None,
        "gameLabel": "",
        "allowDraw": False,
        "playerFields": [],
        "activityFields": fields,
        "aggregations": aggregations,
    }


ATTENDANCE_ONLY = {
    "kind": "none",
    "unit": "",
    "bestOf": None,
    "gameLabel": "",
    "allowDraw": False,
    "playerFields": [],
    "activityFields": [],
    "aggregations": [],
}

DISTANCE_KM = {"key": "distance_km", "label": "Distance", "unit": "km", "type": "number", "min": 0.1, "max": 500, "required": True}
DURATION_MIN = {"key": "duration_min", "label": "Duration", "unit": "min", "type": "number", "min": 1, "max": 2880, "required": True}


def _sport(
    sport_id: str,
    name: str,
    category: str,
    icon: str,
    *,
    booking: bool,
    queue: bool,
    resources: list[str],
    players: tuple[int, int],
    formats: list[dict],
    match_type: str,
    kinds: list[str],
    scoring: dict,
    queue_modes: tuple[str, ...] = (),
    levels: list[str] | None = None,
    routes: bool = False,
    kind_labels: dict | None = None,
) -> dict:
    return {
        "id": sport_id,
        "name": name,
        "category_id": category,
        "icon": icon,
        "booking_eligible": booking,
        "queue_eligible": queue,
        "resource_types": resources,
        "player_config": {"minPlayers": players[0], "maxPlayers": players[1], "teamFormats": formats},
        "match_format": {
            "type": match_type,
            "sessionKinds": kinds,
            "queueModes": list(queue_modes),
            "skillLevels": levels or GENERAL_LEVELS,
            "usesRoutes": routes,
            "kindLabels": kind_labels or {},
        },
        "scoring_config": scoring,
    }


RALLY_KINDS = ["open_play", "challenge", "tournament", "event"]
TEAM_KINDS = ["pickup_game", "open_play", "tournament", "event"]
CLASS_KINDS = ["class", "event"]
COMBAT_KINDS = ["class", "sparring", "event"]
ROTATION = ("rotation", "winner_stays")

SPORTS = [
    # Racket and paddle
    _sport(
        "pickleball",
        "Pickleball",
        "racket_paddle",
        "cm:pickleball",
        booking=True,
        queue=True,
        resources=["court"],
        players=(2, 4),
        formats=SINGLES_DOUBLES,
        match_type="two_sided",
        kinds=RALLY_KINDS,
        queue_modes=ROTATION,
        levels=["All levels", "2.0–2.5", "3.0", "3.5", "4.0", "4.5+"],
        scoring=_two_sided("games", "points", best_of=3, game_label="Games"),
    ),
    _sport(
        "badminton",
        "Badminton",
        "racket_paddle",
        "🏸",
        booking=True,
        queue=True,
        resources=["court"],
        players=(2, 4),
        formats=SINGLES_DOUBLES,
        match_type="two_sided",
        kinds=RALLY_KINDS,
        queue_modes=ROTATION,
        scoring=_two_sided("games", "points", best_of=3, game_label="Games"),
    ),
    _sport(
        "tennis",
        "Tennis",
        "racket_paddle",
        "🎾",
        booking=True,
        queue=True,
        resources=["court"],
        players=(2, 4),
        formats=SINGLES_DOUBLES,
        match_type="two_sided",
        kinds=RALLY_KINDS,
        queue_modes=ROTATION,
        scoring=_two_sided("games", "games", best_of=3, game_label="Sets"),
    ),
    _sport(
        "table_tennis",
        "Table Tennis",
        "racket_paddle",
        "🏓",
        booking=True,
        queue=True,
        resources=["table"],
        players=(2, 4),
        formats=_formats(("singles", "Singles", 1), ("doubles", "Doubles", 2)),
        match_type="two_sided",
        kinds=RALLY_KINDS,
        queue_modes=ROTATION,
        scoring=_two_sided("games", "points", best_of=5, game_label="Games"),
    ),
    # Team and court
    _sport(
        "basketball",
        "Basketball",
        "team_court",
        "🏀",
        booking=True,
        queue=True,
        resources=["court", "half_court"],
        players=(2, 30),
        formats=_formats(("5v5", "5 v 5 full court", 5), ("3x3", "3 x 3 half court", 3), ("4v4", "4 v 4", 4)),
        match_type="two_sided",
        kinds=TEAM_KINDS,
        queue_modes=("winner_stays", "rotation"),
        scoring=_two_sided("total", "points", player_fields=[("points", "Points"), ("rebounds", "Rebounds"), ("assists", "Assists")]),
    ),
    _sport(
        "volleyball",
        "Volleyball",
        "team_court",
        "🏐",
        booking=True,
        queue=True,
        resources=["court"],
        players=(4, 36),
        formats=_formats(("6v6", "6 v 6", 6), ("4v4", "4 v 4", 4)),
        match_type="two_sided",
        kinds=TEAM_KINDS,
        queue_modes=("winner_stays", "rotation"),
        scoring=_two_sided("games", "points", best_of=5, game_label="Sets"),
    ),
    _sport(
        "football",
        "Football / Soccer",
        "team_court",
        "⚽",
        booking=True,
        queue=False,
        resources=["field", "half_field"],
        players=(6, 44),
        formats=_formats(("11v11", "11-a-side", 11), ("7v7", "7-a-side", 7), ("5v5", "Futsal 5-a-side", 5)),
        match_type="two_sided",
        kinds=TEAM_KINDS,
        scoring=_two_sided("total", "goals", allow_draw=True, player_fields=[("goals", "Goals"), ("assists", "Assists")]),
    ),
    # Bat, ball and field
    _sport(
        "baseball",
        "Baseball",
        "bat_field",
        "⚾",
        booking=True,
        queue=False,
        resources=["field"],
        players=(10, 40),
        formats=_formats(("9v9", "9 v 9", 9)),
        match_type="two_sided",
        kinds=TEAM_KINDS,
        scoring=_two_sided("total", "runs", player_fields=[("hits", "Hits"), ("runs", "Runs"), ("rbi", "RBI")]),
    ),
    _sport(
        "softball",
        "Softball",
        "bat_field",
        "🥎",
        booking=True,
        queue=False,
        resources=["field"],
        players=(10, 40),
        formats=_formats(("9v9", "Fastpitch 9 v 9", 9), ("10v10", "Slow-pitch 10 v 10", 10)),
        match_type="two_sided",
        kinds=TEAM_KINDS,
        scoring=_two_sided("total", "runs", player_fields=[("hits", "Hits"), ("runs", "Runs"), ("rbi", "RBI")]),
    ),
    # Indoor and recreational
    _sport(
        "bowling",
        "Bowling",
        "indoor_recreational",
        "🎳",
        booking=True,
        queue=False,
        resources=["lane"],
        players=(1, 8),
        formats=_formats(("individual", "Individual", 1)),
        match_type="individual",
        kinds=["open_play", "tournament", "event"],
        scoring=_individual(
            [{"key": "score", "label": "Game score", "unit": "pins", "type": "integer", "min": 0, "max": 300, "required": True}],
            [
                {"key": "games", "label": "Games played", "op": "count"},
                {"key": "average", "label": "Average score", "op": "avg", "field": "score", "decimals": 0},
                {"key": "best", "label": "Personal best", "op": "max", "field": "score"},
            ],
        ),
    ),
    _sport(
        "billiards",
        "Billiards / Pool",
        "indoor_recreational",
        "🎱",
        booking=True,
        queue=True,
        resources=["table"],
        players=(2, 4),
        formats=_formats(("singles", "Singles", 1), ("doubles", "Doubles", 2)),
        match_type="two_sided",
        kinds=RALLY_KINDS,
        queue_modes=("winner_stays", "rotation"),
        scoring=_two_sided("total", "racks"),
    ),
    _sport(
        "darts",
        "Darts",
        "indoor_recreational",
        "🎯",
        booking=True,
        queue=True,
        resources=["station", "other"],
        players=(2, 4),
        formats=_formats(("singles", "Singles", 1), ("doubles", "Doubles", 2)),
        match_type="two_sided",
        kinds=RALLY_KINDS,
        queue_modes=("winner_stays", "rotation"),
        scoring=_two_sided("total", "legs"),
    ),
    _sport(
        "chess",
        "Chess",
        "indoor_recreational",
        "♟️",
        booking=True,
        queue=False,
        resources=["table"],
        players=(2, 2),
        formats=_formats(("1v1", "One on one", 1)),
        match_type="two_sided",
        kinds=["open_play", "challenge", "tournament", "event"],
        scoring=_two_sided("result", "", allow_draw=True),
    ),
    _sport(
        "esports",
        "Esports",
        "indoor_recreational",
        "🎮",
        booking=True,
        queue=False,
        resources=["station", "other"],
        players=(2, 12),
        formats=_formats(("1v1", "1 v 1", 1), ("5v5", "5 v 5", 5)),
        match_type="two_sided",
        kinds=["open_play", "challenge", "tournament", "event"],
        scoring=_two_sided("total", "maps"),
    ),
    # Fitness and activity-based
    _sport(
        "running",
        "Running",
        "fitness_activity",
        "🏃",
        booking=False,
        queue=False,
        resources=["track"],
        players=(1, 500),
        formats=_formats(("individual", "Individual", 1)),
        match_type="group",
        kinds=["group_activity", "event"],
        routes=True,
        kind_labels={"group_activity": "Group run"},
        scoring=_individual(
            [DISTANCE_KM, DURATION_MIN],
            [
                {"key": "activities", "label": "Runs logged", "op": "count"},
                {"key": "distance", "label": "Total distance", "op": "sum", "field": "distance_km", "unit": "km", "decimals": 1},
                {"key": "duration", "label": "Total time", "op": "sum", "field": "duration_min", "unit": "min", "decimals": 0},
                {"key": "pace", "label": "Average pace", "op": "pace", "unit": "min/km", "decimals": 2},
                {"key": "longest", "label": "Longest run", "op": "max", "field": "distance_km", "unit": "km", "decimals": 1},
            ],
        ),
    ),
    _sport(
        "cycling",
        "Cycling",
        "fitness_activity",
        "🚴",
        booking=False,
        queue=False,
        resources=["track"],
        players=(1, 500),
        formats=_formats(("individual", "Individual", 1)),
        match_type="group",
        kinds=["group_activity", "event"],
        routes=True,
        kind_labels={"group_activity": "Group ride"},
        scoring=_individual(
            [DISTANCE_KM, DURATION_MIN],
            [
                {"key": "activities", "label": "Rides logged", "op": "count"},
                {"key": "distance", "label": "Total distance", "op": "sum", "field": "distance_km", "unit": "km", "decimals": 1},
                {"key": "duration", "label": "Total time", "op": "sum", "field": "duration_min", "unit": "min", "decimals": 0},
                {"key": "speed", "label": "Average speed", "op": "speed", "unit": "km/h", "decimals": 1},
                {"key": "longest", "label": "Longest ride", "op": "max", "field": "distance_km", "unit": "km", "decimals": 1},
            ],
        ),
    ),
    _sport(
        "swimming",
        "Swimming",
        "fitness_activity",
        "🏊",
        booking=True,
        queue=False,
        resources=["pool", "pool_lane"],
        players=(1, 60),
        formats=_formats(("individual", "Individual", 1)),
        match_type="group",
        kinds=["open_play", "class", "event"],
        kind_labels={"open_play": "Lap swim"},
        scoring=_individual(
            [
                {"key": "distance_m", "label": "Distance", "unit": "m", "type": "number", "min": 25, "max": 50000, "required": True},
                {**DURATION_MIN, "required": False},
            ],
            [
                {"key": "activities", "label": "Swims logged", "op": "count"},
                {"key": "distance", "label": "Total distance", "op": "sum", "field": "distance_m", "unit": "m", "decimals": 0},
                {"key": "longest", "label": "Longest swim", "op": "max", "field": "distance_m", "unit": "m", "decimals": 0},
            ],
        ),
    ),
    _sport(
        "martial_arts",
        "Martial Arts",
        "fitness_activity",
        "🥋",
        booking=True,
        queue=False,
        resources=["training_area", "studio"],
        players=(1, 40),
        formats=_formats(("individual", "Individual", 1)),
        match_type="class",
        kinds=COMBAT_KINDS,
        scoring=ATTENDANCE_ONLY,
    ),
    _sport(
        "boxing",
        "Boxing",
        "fitness_activity",
        "🥊",
        booking=True,
        queue=False,
        resources=["ring", "training_area"],
        players=(1, 40),
        formats=_formats(("individual", "Individual", 1)),
        match_type="class",
        kinds=COMBAT_KINDS,
        scoring=ATTENDANCE_ONLY,
    ),
    _sport(
        "muay_thai",
        "Muay Thai",
        "fitness_activity",
        "🥊",
        booking=True,
        queue=False,
        resources=["ring", "training_area"],
        players=(1, 40),
        formats=_formats(("individual", "Individual", 1)),
        match_type="class",
        kinds=COMBAT_KINDS,
        scoring=ATTENDANCE_ONLY,
    ),
    _sport(
        "bjj",
        "Brazilian Jiu-Jitsu",
        "fitness_activity",
        "🥋",
        booking=True,
        queue=False,
        resources=["training_area"],
        players=(1, 40),
        formats=_formats(("individual", "Individual", 1)),
        match_type="class",
        kinds=COMBAT_KINDS,
        levels=["All levels", "White belt", "Blue belt", "Purple belt and up"],
        kind_labels={"sparring": "Open mat"},
        scoring=ATTENDANCE_ONLY,
    ),
    _sport(
        "taekwondo",
        "Taekwondo",
        "fitness_activity",
        "🥋",
        booking=True,
        queue=False,
        resources=["training_area", "studio"],
        players=(1, 40),
        formats=_formats(("individual", "Individual", 1)),
        match_type="class",
        kinds=COMBAT_KINDS,
        scoring=ATTENDANCE_ONLY,
    ),
    _sport(
        "dance_fitness",
        "Dance Fitness",
        "fitness_activity",
        "💃",
        booking=True,
        queue=False,
        resources=["studio"],
        players=(1, 80),
        formats=_formats(("individual", "Individual", 1)),
        match_type="class",
        kinds=CLASS_KINDS,
        scoring=ATTENDANCE_ONLY,
    ),
    _sport(
        "yoga",
        "Yoga",
        "fitness_activity",
        "🧘",
        booking=True,
        queue=False,
        resources=["studio"],
        players=(1, 60),
        formats=_formats(("individual", "Individual", 1)),
        match_type="class",
        kinds=CLASS_KINDS,
        scoring=ATTENDANCE_ONLY,
    ),
    _sport(
        "calisthenics",
        "Calisthenics",
        "fitness_activity",
        "🤸",
        booking=True,
        queue=False,
        resources=["training_area"],
        players=(1, 40),
        formats=_formats(("individual", "Individual", 1)),
        match_type="class",
        kinds=["class", "open_play", "event"],
        kind_labels={"open_play": "Open training"},
        scoring=ATTENDANCE_ONLY,
    ),
    _sport(
        "climbing",
        "Wall Climbing / Bouldering",
        "fitness_activity",
        "🧗",
        booking=True,
        queue=False,
        resources=["climbing_wall"],
        players=(1, 40),
        formats=_formats(("individual", "Individual", 1)),
        match_type="class",
        kinds=["open_play", "class", "event"],
        kind_labels={"open_play": "Open climb"},
        scoring=ATTENDANCE_ONLY,
    ),
    # Outdoor and specialty
    _sport(
        "golf",
        "Golf",
        "outdoor_specialty",
        "⛳",
        booking=True,
        queue=False,
        resources=["tee"],
        players=(1, 4),
        formats=_formats(("individual", "Stroke play", 1)),
        match_type="individual",
        kinds=["tee_time", "tournament", "event"],
        scoring=_individual(
            [
                {"key": "strokes", "label": "Strokes", "unit": "strokes", "type": "integer", "min": 18, "max": 250, "required": True},
                {"key": "holes", "label": "Holes played", "unit": "holes", "type": "integer", "min": 9, "max": 18, "required": True},
            ],
            [
                {"key": "rounds", "label": "Rounds logged", "op": "count"},
                {"key": "best", "label": "Best round", "op": "min", "field": "strokes", "unit": "strokes"},
                {"key": "average", "label": "Average strokes", "op": "avg", "field": "strokes", "decimals": 1},
            ],
        ),
    ),
    _sport(
        "skating",
        "Skating",
        "outdoor_specialty",
        "⛸️",
        booking=True,
        queue=False,
        resources=["skate_park", "track", "other"],
        players=(1, 100),
        formats=_formats(("individual", "Individual", 1)),
        match_type="group",
        kinds=["group_activity", "class", "event"],
        kind_labels={"group_activity": "Group skate"},
        scoring=ATTENDANCE_ONLY,
    ),
    _sport(
        "skateboarding",
        "Skateboarding",
        "outdoor_specialty",
        "🛹",
        booking=False,
        queue=False,
        resources=["skate_park"],
        players=(1, 100),
        formats=_formats(("individual", "Individual", 1)),
        match_type="group",
        kinds=["group_activity", "class", "event"],
        kind_labels={"group_activity": "Skate meetup"},
        scoring=ATTENDANCE_ONLY,
    ),
    _sport(
        "beach_volleyball",
        "Beach Volleyball",
        "outdoor_specialty",
        "🏐",
        booking=True,
        queue=True,
        resources=["court"],
        players=(4, 24),
        formats=_formats(("2v2", "2 v 2", 2), ("4v4", "4 v 4", 4)),
        match_type="two_sided",
        kinds=TEAM_KINDS,
        queue_modes=("winner_stays", "rotation"),
        scoring=_two_sided("games", "points", best_of=3, game_label="Sets"),
    ),
]
