"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-08 11:42:50.382463
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "geo_regions",
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("region_name", sa.String(length=120), nullable=False),
        sa.Column("island_group", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_geo_regions")),
    )
    op.create_table(
        "resource_types",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resource_types")),
        sa.UniqueConstraint("name", name=op.f("uq_resource_types_name")),
    )
    op.create_table(
        "sport_categories",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sport_categories")),
        sa.UniqueConstraint("name", name=op.f("uq_sport_categories_name")),
    )
    op.create_table(
        "geo_provinces",
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("region_code", sa.String(length=10), nullable=False),
        sa.ForeignKeyConstraint(["region_code"], ["geo_regions.code"], name=op.f("fk_geo_provinces_region_code_geo_regions")),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_geo_provinces")),
    )
    op.create_index(op.f("ix_geo_provinces_region_code"), "geo_provinces", ["region_code"], unique=False)
    op.create_table(
        "sports",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("category_id", sa.String(length=40), nullable=False),
        sa.Column("icon", sa.String(length=40), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("booking_eligible", sa.Boolean(), nullable=False),
        sa.Column("queue_eligible", sa.Boolean(), nullable=False),
        sa.Column("player_config", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False),
        sa.Column("match_format", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False),
        sa.Column("scoring_config", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False),
        sa.Column("resource_types", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["sport_categories.id"], name=op.f("fk_sports_category_id_sport_categories")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sports")),
        sa.UniqueConstraint("name", name=op.f("uq_sports_name")),
    )
    op.create_index(op.f("ix_sports_category_id"), "sports", ["category_id"], unique=False)
    op.create_table(
        "geo_cities",
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("region_code", sa.String(length=10), nullable=False),
        sa.Column("province_code", sa.String(length=10), nullable=True),
        sa.Column("is_city", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["province_code"], ["geo_provinces.code"], name=op.f("fk_geo_cities_province_code_geo_provinces")),
        sa.ForeignKeyConstraint(["region_code"], ["geo_regions.code"], name=op.f("fk_geo_cities_region_code_geo_regions")),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_geo_cities")),
    )
    op.create_index(op.f("ix_geo_cities_name"), "geo_cities", ["name"], unique=False)
    op.create_index(op.f("ix_geo_cities_province_code"), "geo_cities", ["province_code"], unique=False)
    op.create_index(op.f("ix_geo_cities_region_code"), "geo_cities", ["region_code"], unique=False)
    op.create_table(
        "geo_barangays",
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("city_code", sa.String(length=10), nullable=False),
        sa.ForeignKeyConstraint(["city_code"], ["geo_cities.code"], name=op.f("fk_geo_barangays_city_code_geo_cities")),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_geo_barangays")),
    )
    op.create_index(op.f("ix_geo_barangays_city_code"), "geo_barangays", ["city_code"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("display_name", sa.String(length=80), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("bio", sa.Text(), nullable=False),
        sa.Column("city_code", sa.String(length=10), nullable=True),
        sa.Column("avatar_color", sa.String(length=9), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("role IN ('player', 'admin')", name=op.f("ck_users_role")),
        sa.ForeignKeyConstraint(["city_code"], ["geo_cities.code"], name=op.f("fk_users_city_code_geo_cities")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "auth_tokens",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_auth_tokens_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_auth_tokens_token_hash")),
    )
    op.create_index(op.f("ix_auth_tokens_user_id"), "auth_tokens", ["user_id"], unique=False)
    op.create_table(
        "communities",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=140), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("region_code", sa.String(length=10), nullable=True),
        sa.Column("province_code", sa.String(length=10), nullable=True),
        sa.Column("city_code", sa.String(length=10), nullable=True),
        sa.Column("owner_user_id", sa.String(length=32), nullable=False),
        sa.Column("visibility", sa.String(length=16), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("visibility IN ('public', 'private')", name=op.f("ck_communities_visibility")),
        sa.ForeignKeyConstraint(["city_code"], ["geo_cities.code"], name=op.f("fk_communities_city_code_geo_cities")),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], name=op.f("fk_communities_owner_user_id_users")),
        sa.ForeignKeyConstraint(["province_code"], ["geo_provinces.code"], name=op.f("fk_communities_province_code_geo_provinces")),
        sa.ForeignKeyConstraint(["region_code"], ["geo_regions.code"], name=op.f("fk_communities_region_code_geo_regions")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_communities")),
        sa.UniqueConstraint("name", name=op.f("uq_communities_name")),
        sa.UniqueConstraint("slug", name=op.f("uq_communities_slug")),
    )
    op.create_index(op.f("ix_communities_city_code"), "communities", ["city_code"], unique=False)
    op.create_table(
        "facilities",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("address_line", sa.String(length=255), nullable=False),
        sa.Column("region_code", sa.String(length=10), nullable=False),
        sa.Column("province_code", sa.String(length=10), nullable=True),
        sa.Column("city_code", sa.String(length=10), nullable=False),
        sa.Column("barangay_code", sa.String(length=10), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("amenities", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False),
        sa.Column("photos", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False),
        sa.Column("verification_status", sa.String(length=16), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("owner_user_id", sa.String(length=32), nullable=False),
        sa.Column("contact_name", sa.String(length=120), nullable=False),
        sa.Column("contact_email", sa.String(length=254), nullable=False),
        sa.Column("contact_phone", sa.String(length=40), nullable=False),
        sa.Column("verification_notes", sa.Text(), nullable=False),
        sa.Column("requires_approval", sa.Boolean(), nullable=False),
        sa.Column("min_notice_minutes", sa.Integer(), nullable=False),
        sa.Column("max_advance_days", sa.Integer(), nullable=False),
        sa.Column("cancellation_window_hours", sa.Integer(), nullable=False),
        sa.Column("min_booking_minutes", sa.Integer(), nullable=False),
        sa.Column("max_booking_minutes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "verification_status IN ('pending', 'verified', 'rejected', 'suspended')", name=op.f("ck_facilities_verification_status")
        ),
        sa.CheckConstraint("cancellation_window_hours >= 0", name=op.f("ck_facilities_cancellation_window_non_negative")),
        sa.CheckConstraint("latitude IS NULL OR (latitude BETWEEN -90 AND 90)", name=op.f("ck_facilities_latitude_range")),
        sa.CheckConstraint("longitude IS NULL OR (longitude BETWEEN -180 AND 180)", name=op.f("ck_facilities_longitude_range")),
        sa.CheckConstraint("max_advance_days BETWEEN 1 AND 365", name=op.f("ck_facilities_max_advance_range")),
        sa.CheckConstraint(
            "min_booking_minutes > 0 AND max_booking_minutes >= min_booking_minutes", name=op.f("ck_facilities_booking_duration_range")
        ),
        sa.CheckConstraint("min_notice_minutes >= 0", name=op.f("ck_facilities_min_notice_non_negative")),
        sa.ForeignKeyConstraint(["barangay_code"], ["geo_barangays.code"], name=op.f("fk_facilities_barangay_code_geo_barangays")),
        sa.ForeignKeyConstraint(["city_code"], ["geo_cities.code"], name=op.f("fk_facilities_city_code_geo_cities")),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], name=op.f("fk_facilities_owner_user_id_users")),
        sa.ForeignKeyConstraint(["province_code"], ["geo_provinces.code"], name=op.f("fk_facilities_province_code_geo_provinces")),
        sa.ForeignKeyConstraint(["region_code"], ["geo_regions.code"], name=op.f("fk_facilities_region_code_geo_regions")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_facilities")),
        sa.UniqueConstraint("slug", name=op.f("uq_facilities_slug")),
    )
    op.create_index("ix_facilities_location", "facilities", ["region_code", "province_code", "city_code"], unique=False)
    op.create_index(op.f("ix_facilities_verification_status"), "facilities", ["verification_status"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("link", sa.String(length=255), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_notifications_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index("ix_notifications_user_created", "notifications", ["user_id", "created_at"], unique=False)
    op.create_table(
        "user_sports",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("sport_id", sa.String(length=40), nullable=False),
        sa.Column("skill_level", sa.String(length=40), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["sport_id"], ["sports.id"], name=op.f("fk_user_sports_sport_id_sports"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_user_sports_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "sport_id", name=op.f("pk_user_sports")),
    )
    op.create_table(
        "community_members",
        sa.Column("community_id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("role IN ('owner', 'admin', 'member')", name=op.f("ck_community_members_role")),
        sa.ForeignKeyConstraint(
            ["community_id"], ["communities.id"], name=op.f("fk_community_members_community_id_communities"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_community_members_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("community_id", "user_id", name=op.f("pk_community_members")),
    )
    op.create_index(op.f("ix_community_members_user_id"), "community_members", ["user_id"], unique=False)
    op.create_table(
        "community_sports",
        sa.Column("community_id", sa.String(length=32), nullable=False),
        sa.Column("sport_id", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["community_id"], ["communities.id"], name=op.f("fk_community_sports_community_id_communities"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["sport_id"], ["sports.id"], name=op.f("fk_community_sports_sport_id_sports")),
        sa.PrimaryKeyConstraint("community_id", "sport_id", name=op.f("pk_community_sports")),
    )
    op.create_index(op.f("ix_community_sports_sport_id"), "community_sports", ["sport_id"], unique=False)
    op.create_table(
        "facility_hours",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("facility_id", sa.String(length=32), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=False),
        sa.Column("open_minute", sa.Integer(), nullable=False),
        sa.Column("close_minute", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "close_minute BETWEEN 15 AND 1440 AND close_minute > open_minute", name=op.f("ck_facility_hours_close_after_open")
        ),
        sa.CheckConstraint("open_minute % 15 = 0 AND close_minute % 15 = 0", name=op.f("ck_facility_hours_quarter_hour")),
        sa.CheckConstraint("open_minute BETWEEN 0 AND 1425", name=op.f("ck_facility_hours_open_range")),
        sa.CheckConstraint("weekday BETWEEN 0 AND 6", name=op.f("ck_facility_hours_weekday_range")),
        sa.ForeignKeyConstraint(
            ["facility_id"], ["facilities.id"], name=op.f("fk_facility_hours_facility_id_facilities"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_facility_hours")),
        sa.UniqueConstraint("facility_id", "weekday", name="uq_facility_hours_facility_weekday"),
    )
    op.create_index(op.f("ix_facility_hours_facility_id"), "facility_hours", ["facility_id"], unique=False)
    op.create_table(
        "facility_sports",
        sa.Column("facility_id", sa.String(length=32), nullable=False),
        sa.Column("sport_id", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["facility_id"], ["facilities.id"], name=op.f("fk_facility_sports_facility_id_facilities"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["sport_id"], ["sports.id"], name=op.f("fk_facility_sports_sport_id_sports")),
        sa.PrimaryKeyConstraint("facility_id", "sport_id", name=op.f("pk_facility_sports")),
    )
    op.create_index(op.f("ix_facility_sports_sport_id"), "facility_sports", ["sport_id"], unique=False)
    op.create_table(
        "facility_staff",
        sa.Column("facility_id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.CheckConstraint("role IN ('owner', 'manager')", name=op.f("ck_facility_staff_role")),
        sa.ForeignKeyConstraint(
            ["facility_id"], ["facilities.id"], name=op.f("fk_facility_staff_facility_id_facilities"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_facility_staff_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("facility_id", "user_id", name=op.f("pk_facility_staff")),
    )
    op.create_index(op.f("ix_facility_staff_user_id"), "facility_staff", ["user_id"], unique=False)
    op.create_table(
        "resources",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("facility_id", sa.String(length=32), nullable=False),
        sa.Column("parent_id", sa.String(length=32), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("resource_type_id", sa.String(length=40), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("slot_minutes", sa.Integer(), nullable=False),
        sa.Column("hourly_rate_centavos", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.CheckConstraint("capacity > 0", name=op.f("ck_resources_capacity_positive")),
        sa.CheckConstraint("hourly_rate_centavos >= 0", name=op.f("ck_resources_rate_non_negative")),
        sa.CheckConstraint("slot_minutes > 0 AND slot_minutes % 15 = 0", name=op.f("ck_resources_slot_quarter_hour")),
        sa.ForeignKeyConstraint(["facility_id"], ["facilities.id"], name=op.f("fk_resources_facility_id_facilities"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_id"], ["resources.id"], name=op.f("fk_resources_parent_id_resources"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["resource_type_id"], ["resource_types.id"], name=op.f("fk_resources_resource_type_id_resource_types")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resources")),
        sa.UniqueConstraint("facility_id", "name", name="uq_resources_facility_name"),
    )
    op.create_index(op.f("ix_resources_facility_id"), "resources", ["facility_id"], unique=False)
    op.create_index(op.f("ix_resources_parent_id"), "resources", ["parent_id"], unique=False)
    op.create_table(
        "teams",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("sport_id", sa.String(length=40), nullable=False),
        sa.Column("community_id", sa.String(length=32), nullable=True),
        sa.Column("captain_user_id", sa.String(length=32), nullable=False),
        sa.Column("city_code", sa.String(length=10), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["captain_user_id"], ["users.id"], name=op.f("fk_teams_captain_user_id_users")),
        sa.ForeignKeyConstraint(["city_code"], ["geo_cities.code"], name=op.f("fk_teams_city_code_geo_cities")),
        sa.ForeignKeyConstraint(["community_id"], ["communities.id"], name=op.f("fk_teams_community_id_communities"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["sport_id"], ["sports.id"], name=op.f("fk_teams_sport_id_sports")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teams")),
        sa.UniqueConstraint("name", "sport_id", name="uq_teams_name_sport"),
    )
    op.create_index(op.f("ix_teams_community_id"), "teams", ["community_id"], unique=False)
    op.create_index(op.f("ix_teams_sport_id"), "teams", ["sport_id"], unique=False)
    op.create_table(
        "reservations",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("resource_id", sa.String(length=32), nullable=False),
        sa.Column("facility_id", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("organizer_user_id", sa.String(length=32), nullable=False),
        sa.Column("sport_id", sa.String(length=40), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("price_centavos", sa.Integer(), nullable=False),
        sa.Column("payment_status", sa.String(length=16), nullable=False),
        sa.Column("party_size", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("free_cancel_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("late_cancellation", sa.Boolean(), nullable=False),
        sa.Column("series_id", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by_user_id", sa.String(length=32), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_reason", sa.Text(), nullable=False),
        sa.CheckConstraint("kind IN ('booking', 'block')", name=op.f("ck_reservations_kind")),
        sa.CheckConstraint(
            "payment_status IN ('not_required', 'pay_at_venue', 'paid', 'refunded')", name=op.f("ck_reservations_payment_status")
        ),
        sa.CheckConstraint("status IN ('pending', 'confirmed', 'rejected', 'cancelled')", name=op.f("ck_reservations_status")),
        sa.CheckConstraint("end_at > start_at", name=op.f("ck_reservations_time_order")),
        sa.CheckConstraint("party_size > 0", name=op.f("ck_reservations_party_positive")),
        sa.CheckConstraint("price_centavos >= 0", name=op.f("ck_reservations_price_non_negative")),
        sa.ForeignKeyConstraint(["decided_by_user_id"], ["users.id"], name=op.f("fk_reservations_decided_by_user_id_users")),
        sa.ForeignKeyConstraint(["facility_id"], ["facilities.id"], name=op.f("fk_reservations_facility_id_facilities")),
        sa.ForeignKeyConstraint(["organizer_user_id"], ["users.id"], name=op.f("fk_reservations_organizer_user_id_users")),
        sa.ForeignKeyConstraint(["resource_id"], ["resources.id"], name=op.f("fk_reservations_resource_id_resources")),
        sa.ForeignKeyConstraint(["sport_id"], ["sports.id"], name=op.f("fk_reservations_sport_id_sports")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reservations")),
    )
    op.create_index("ix_reservations_facility_start", "reservations", ["facility_id", "start_at"], unique=False)
    op.create_index("ix_reservations_organizer_start", "reservations", ["organizer_user_id", "start_at"], unique=False)
    op.create_index("ix_reservations_resource_start", "reservations", ["resource_id", "start_at"], unique=False)
    op.create_index(op.f("ix_reservations_series_id"), "reservations", ["series_id"], unique=False)
    op.create_table(
        "resource_sports",
        sa.Column("resource_id", sa.String(length=32), nullable=False),
        sa.Column("sport_id", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["resource_id"], ["resources.id"], name=op.f("fk_resource_sports_resource_id_resources"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["sport_id"], ["sports.id"], name=op.f("fk_resource_sports_sport_id_sports")),
        sa.PrimaryKeyConstraint("resource_id", "sport_id", name=op.f("pk_resource_sports")),
    )
    op.create_table(
        "team_members",
        sa.Column("team_id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("role IN ('captain', 'member')", name=op.f("ck_team_members_role")),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], name=op.f("fk_team_members_team_id_teams"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_team_members_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("team_id", "user_id", name=op.f("pk_team_members")),
    )
    op.create_index(op.f("ix_team_members_user_id"), "team_members", ["user_id"], unique=False)
    op.create_table(
        "play_sessions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("sport_id", sa.String(length=40), nullable=False),
        sa.Column("facility_id", sa.String(length=32), nullable=True),
        sa.Column("reservation_id", sa.String(length=32), nullable=True),
        sa.Column("host_user_id", sa.String(length=32), nullable=False),
        sa.Column("community_id", sa.String(length=32), nullable=True),
        sa.Column("series_id", sa.String(length=32), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("min_players", sa.Integer(), nullable=False),
        sa.Column("confirmed_count", sa.Integer(), nullable=False),
        sa.Column("skill_level", sa.String(length=40), nullable=False),
        sa.Column("team_format", sa.String(length=40), nullable=False),
        sa.Column("gender_eligibility", sa.String(length=16), nullable=False),
        sa.Column("fee_centavos", sa.Integer(), nullable=False),
        sa.Column("join_policy", sa.String(length=16), nullable=False),
        sa.Column("queue_mode", sa.String(length=16), nullable=False),
        sa.Column("courts_in_play", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("venue_name", sa.String(length=160), nullable=False),
        sa.Column("meetup_note", sa.Text(), nullable=False),
        sa.Column("route_name", sa.String(length=160), nullable=False),
        sa.Column("route_distance_km", sa.Float(), nullable=True),
        sa.Column("region_code", sa.String(length=10), nullable=False),
        sa.Column("province_code", sa.String(length=10), nullable=True),
        sa.Column("city_code", sa.String(length=10), nullable=False),
        sa.Column("barangay_code", sa.String(length=10), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_reason", sa.Text(), nullable=False),
        sa.CheckConstraint("gender_eligibility IN ('open', 'women', 'men', 'mixed')", name=op.f("ck_play_sessions_gender_eligibility")),
        sa.CheckConstraint("join_policy IN ('open', 'approval')", name=op.f("ck_play_sessions_join_policy")),
        sa.CheckConstraint(
            "kind IN ('open_play', 'pickup_game', 'class', 'sparring', 'group_activity', 'tee_time', 'challenge', 'tournament', 'event')",
            name=op.f("ck_play_sessions_kind"),
        ),
        sa.CheckConstraint("queue_mode IN ('none', 'rotation', 'winner_stays')", name=op.f("ck_play_sessions_queue_mode")),
        sa.CheckConstraint("status IN ('scheduled', 'live', 'completed', 'cancelled')", name=op.f("ck_play_sessions_status")),
        sa.CheckConstraint("capacity > 0", name=op.f("ck_play_sessions_capacity_positive")),
        sa.CheckConstraint("confirmed_count >= 0 AND confirmed_count <= capacity", name=op.f("ck_play_sessions_confirmed_within_capacity")),
        sa.CheckConstraint("courts_in_play >= 1", name=op.f("ck_play_sessions_courts_positive")),
        sa.CheckConstraint("end_at > start_at", name=op.f("ck_play_sessions_time_order")),
        sa.CheckConstraint("fee_centavos >= 0", name=op.f("ck_play_sessions_fee_non_negative")),
        sa.CheckConstraint("min_players >= 1 AND min_players <= capacity", name=op.f("ck_play_sessions_min_players_range")),
        sa.ForeignKeyConstraint(["barangay_code"], ["geo_barangays.code"], name=op.f("fk_play_sessions_barangay_code_geo_barangays")),
        sa.ForeignKeyConstraint(["city_code"], ["geo_cities.code"], name=op.f("fk_play_sessions_city_code_geo_cities")),
        sa.ForeignKeyConstraint(
            ["community_id"], ["communities.id"], name=op.f("fk_play_sessions_community_id_communities"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["facility_id"], ["facilities.id"], name=op.f("fk_play_sessions_facility_id_facilities")),
        sa.ForeignKeyConstraint(["host_user_id"], ["users.id"], name=op.f("fk_play_sessions_host_user_id_users")),
        sa.ForeignKeyConstraint(["province_code"], ["geo_provinces.code"], name=op.f("fk_play_sessions_province_code_geo_provinces")),
        sa.ForeignKeyConstraint(["region_code"], ["geo_regions.code"], name=op.f("fk_play_sessions_region_code_geo_regions")),
        sa.ForeignKeyConstraint(
            ["reservation_id"], ["reservations.id"], name=op.f("fk_play_sessions_reservation_id_reservations"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["sport_id"], ["sports.id"], name=op.f("fk_play_sessions_sport_id_sports")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_play_sessions")),
    )
    op.create_index(op.f("ix_play_sessions_community_id"), "play_sessions", ["community_id"], unique=False)
    op.create_index("ix_play_sessions_discovery", "play_sessions", ["status", "start_at"], unique=False)
    op.create_index(op.f("ix_play_sessions_facility_id"), "play_sessions", ["facility_id"], unique=False)
    op.create_index(op.f("ix_play_sessions_host_user_id"), "play_sessions", ["host_user_id"], unique=False)
    op.create_index("ix_play_sessions_location", "play_sessions", ["region_code", "province_code", "city_code"], unique=False)
    op.create_index(op.f("ix_play_sessions_series_id"), "play_sessions", ["series_id"], unique=False)
    op.create_index(op.f("ix_play_sessions_sport_id"), "play_sessions", ["sport_id"], unique=False)
    op.create_table(
        "reservation_slots",
        sa.Column("unit_resource_id", sa.String(length=32), nullable=False),
        sa.Column("slot_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reservation_id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["reservation_id"], ["reservations.id"], name=op.f("fk_reservation_slots_reservation_id_reservations"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["unit_resource_id"], ["resources.id"], name=op.f("fk_reservation_slots_unit_resource_id_resources"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("unit_resource_id", "slot_start", name=op.f("pk_reservation_slots")),
    )
    op.create_index(op.f("ix_reservation_slots_reservation_id"), "reservation_slots", ["reservation_id"], unique=False)
    op.create_table(
        "activity_logs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("sport_id", sa.String(length=40), nullable=False),
        sa.Column("session_id", sa.String(length=32), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metrics", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False),
        sa.Column("source", sa.String(length=24), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("source IN ('self_reported', 'organizer_recorded')", name=op.f("ck_activity_logs_source")),
        sa.ForeignKeyConstraint(
            ["session_id"], ["play_sessions.id"], name=op.f("fk_activity_logs_session_id_play_sessions"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["sport_id"], ["sports.id"], name=op.f("fk_activity_logs_sport_id_sports")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_activity_logs_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity_logs")),
    )
    op.create_index("ix_activity_logs_user_sport", "activity_logs", ["user_id", "sport_id", "occurred_at"], unique=False)
    op.create_table(
        "matches",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("sport_id", sa.String(length=40), nullable=False),
        sa.Column("session_id", sa.String(length=32), nullable=True),
        sa.Column("court_label", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("score", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True),
        sa.Column("winner_side", sa.Integer(), nullable=True),
        sa.Column("is_draw", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recorded_by_user_id", sa.String(length=32), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.CheckConstraint("status IN ('in_progress', 'completed', 'void')", name=op.f("ck_matches_status")),
        sa.CheckConstraint("winner_side IS NULL OR winner_side IN (1, 2)", name=op.f("ck_matches_winner_side")),
        sa.ForeignKeyConstraint(["recorded_by_user_id"], ["users.id"], name=op.f("fk_matches_recorded_by_user_id_users")),
        sa.ForeignKeyConstraint(
            ["session_id"], ["play_sessions.id"], name=op.f("fk_matches_session_id_play_sessions"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["sport_id"], ["sports.id"], name=op.f("fk_matches_sport_id_sports")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_matches")),
    )
    op.create_index(op.f("ix_matches_session_id"), "matches", ["session_id"], unique=False)
    op.create_index(op.f("ix_matches_sport_id"), "matches", ["sport_id"], unique=False)
    op.create_table(
        "session_participants",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("session_id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("team_id", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("checked_in", sa.Boolean(), nullable=False),
        sa.Column("queue_state", sa.String(length=16), nullable=False),
        sa.Column("queued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("games_played", sa.Integer(), nullable=False),
        sa.CheckConstraint("queue_state IN ('idle', 'waiting', 'playing')", name=op.f("ck_session_participants_queue_state")),
        sa.CheckConstraint(
            "status IN ('confirmed', 'waitlisted', 'pending', 'left', 'removed', 'declined')", name=op.f("ck_session_participants_status")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["play_sessions.id"], name=op.f("fk_session_participants_session_id_play_sessions"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], name=op.f("fk_session_participants_team_id_teams"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_session_participants_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_participants")),
        sa.UniqueConstraint("session_id", "user_id", name="uq_session_participants_session_user"),
    )
    op.create_index(op.f("ix_session_participants_user_id"), "session_participants", ["user_id"], unique=False)
    op.create_index("ix_session_participants_waitlist", "session_participants", ["session_id", "status", "joined_at"], unique=False)
    op.create_table(
        "match_players",
        sa.Column("match_id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("side", sa.Integer(), nullable=False),
        sa.Column("stats", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False),
        sa.CheckConstraint("side IN (1, 2)", name=op.f("ck_match_players_side")),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], name=op.f("fk_match_players_match_id_matches"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_match_players_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("match_id", "user_id", name=op.f("pk_match_players")),
    )
    op.create_index(op.f("ix_match_players_user_id"), "match_players", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_match_players_user_id"), table_name="match_players")
    op.drop_table("match_players")
    op.drop_index("ix_session_participants_waitlist", table_name="session_participants")
    op.drop_index(op.f("ix_session_participants_user_id"), table_name="session_participants")
    op.drop_table("session_participants")
    op.drop_index(op.f("ix_matches_sport_id"), table_name="matches")
    op.drop_index(op.f("ix_matches_session_id"), table_name="matches")
    op.drop_table("matches")
    op.drop_index("ix_activity_logs_user_sport", table_name="activity_logs")
    op.drop_table("activity_logs")
    op.drop_index(op.f("ix_reservation_slots_reservation_id"), table_name="reservation_slots")
    op.drop_table("reservation_slots")
    op.drop_index(op.f("ix_play_sessions_sport_id"), table_name="play_sessions")
    op.drop_index(op.f("ix_play_sessions_series_id"), table_name="play_sessions")
    op.drop_index("ix_play_sessions_location", table_name="play_sessions")
    op.drop_index(op.f("ix_play_sessions_host_user_id"), table_name="play_sessions")
    op.drop_index(op.f("ix_play_sessions_facility_id"), table_name="play_sessions")
    op.drop_index("ix_play_sessions_discovery", table_name="play_sessions")
    op.drop_index(op.f("ix_play_sessions_community_id"), table_name="play_sessions")
    op.drop_table("play_sessions")
    op.drop_index(op.f("ix_team_members_user_id"), table_name="team_members")
    op.drop_table("team_members")
    op.drop_table("resource_sports")
    op.drop_index(op.f("ix_reservations_series_id"), table_name="reservations")
    op.drop_index("ix_reservations_resource_start", table_name="reservations")
    op.drop_index("ix_reservations_organizer_start", table_name="reservations")
    op.drop_index("ix_reservations_facility_start", table_name="reservations")
    op.drop_table("reservations")
    op.drop_index(op.f("ix_teams_sport_id"), table_name="teams")
    op.drop_index(op.f("ix_teams_community_id"), table_name="teams")
    op.drop_table("teams")
    op.drop_index(op.f("ix_resources_parent_id"), table_name="resources")
    op.drop_index(op.f("ix_resources_facility_id"), table_name="resources")
    op.drop_table("resources")
    op.drop_index(op.f("ix_facility_staff_user_id"), table_name="facility_staff")
    op.drop_table("facility_staff")
    op.drop_index(op.f("ix_facility_sports_sport_id"), table_name="facility_sports")
    op.drop_table("facility_sports")
    op.drop_index(op.f("ix_facility_hours_facility_id"), table_name="facility_hours")
    op.drop_table("facility_hours")
    op.drop_index(op.f("ix_community_sports_sport_id"), table_name="community_sports")
    op.drop_table("community_sports")
    op.drop_index(op.f("ix_community_members_user_id"), table_name="community_members")
    op.drop_table("community_members")
    op.drop_table("user_sports")
    op.drop_index("ix_notifications_user_created", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_facilities_verification_status"), table_name="facilities")
    op.drop_index("ix_facilities_location", table_name="facilities")
    op.drop_table("facilities")
    op.drop_index(op.f("ix_communities_city_code"), table_name="communities")
    op.drop_table("communities")
    op.drop_index(op.f("ix_auth_tokens_user_id"), table_name="auth_tokens")
    op.drop_table("auth_tokens")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_geo_barangays_city_code"), table_name="geo_barangays")
    op.drop_table("geo_barangays")
    op.drop_index(op.f("ix_geo_cities_region_code"), table_name="geo_cities")
    op.drop_index(op.f("ix_geo_cities_province_code"), table_name="geo_cities")
    op.drop_index(op.f("ix_geo_cities_name"), table_name="geo_cities")
    op.drop_table("geo_cities")
    op.drop_index(op.f("ix_sports_category_id"), table_name="sports")
    op.drop_table("sports")
    op.drop_index(op.f("ix_geo_provinces_region_code"), table_name="geo_provinces")
    op.drop_table("geo_provinces")
    op.drop_table("sport_categories")
    op.drop_table("resource_types")
    op.drop_table("geo_regions")
    # ### end Alembic commands ###
